### ISSUE TITLE
[addon-info] stateless component `No propTypes defined!` on prop table in build mode

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1141]
I have a simple stateless [component](https://github.com/Stupidism/stupid-rc-starter/blob/develop/src/RenderCounter/Counter.js):
```
const Counter = ({ count }) => (
  <div style={styles.counter}>{count}</div>
);

Counter.propTypes = {
  count: T.number.isRequired,
};
```
## Expected
It renders normally in dev mode, when I call `start-storybook -p 6006`
![image](https://cloud.githubusercontent.com/assets/5801015/26526053/7ff28876-4321-11e7-9ec0-652b4a2e4e84.png)

## Current
Props are missing in build mode, when I call `build-storybook -o gh-pages`
online demo is [here](https://stupidism.github.io/stupid-rc-starter/?selectedKind=RenderCounter&selectedStory=Counter)

**Comment by shilman** [comment]
@Stupidism what happens when you run the build with `NODE_ENV=development`?

**Comment by Stupidism** [comment]
@shilman I will try and tell you tmr.

**Comment by shilman** [comment]
Seems like something is stripping out the proptypes when the production flag is set. Perhaps a webpack plugin? Haven't had time to dig in, but it seems like something that should be easy to diagnose and fix.

**Comment by Stupidism** [comment]
Things are getting even worse.
![image](https://cloud.githubusercontent.com/assets/5801015/26562213/4ac7d85a-4479-11e7-8bc1-442796e65277.png)

I already fixed it temporarily in my repo. If you want to reproduce it. Just run
```
git clone git@github.com:Stupidism/stupid-rc-starter.git
cd stupid-rc-starter && yarn install
./node_modules/.bin/build-storybook -o gh-pages && npm run gh-pages:opn
```
You will see the bug in `http://localhost:6006/?selectedKind=RenderCounter&selectedStory=Counter`
and `http://localhost:6006/?selectedKind=RenderCounter&selectedStory=StatelessRenderCounter`

**Comment by Stupidism** [comment]
Is there any progress on this?

**Comment by danielduan** [comment]
Related to https://github.com/storybooks/storybook/issues/1661, fixing the docgen part here: https://github.com/storybooks/storybook/pull/1725.

Will require a separate PR to set `NODE_ENV` in Webpack for `prop-types` for components that can't be documented using docgen.

**Comment by Stupidism** [comment]
It seems to be fixed now.

**Comment by feonit** [comment]
It still not worked for me. Here my component:

```js
import React from "react";
import "./Background.css";
import PropTypes from "prop-types";

const Background = (props) => {
	const {children} = props;
	return (
		<div className={"Background"}>
			{children}
		</div>
	)
};

Background.displayName = "Background";

Background.propTypes = {
	/** My content */
	children: PropTypes.any.isRequired
};
export default Background;
```

For command `NODE_ENV=production npm run storybook` i have:
![2019-01-15 18 33 02](https://user-images.githubusercontent.com/3956831/51190821-1d0d2b80-18f4-11e9-88cc-19482e3b85b4.png)

And for `npm run storybook`:
![2019-01-15 18 37 47](https://user-images.githubusercontent.com/3956831/51191077-b3415180-18f4-11e9-9908-dc27deca5b5a.png)

Same for the rest of the components too. But when i add:
```js
Background.defaultProps = {
	children: 'my text'
};
```
 the following happens:
![2019-01-15 18 43 25](https://user-images.githubusercontent.com/3956831/51191471-82ade780-18f5-11e9-86e2-6a7032a33ac2.png)


I use:
```
    "@storybook/addon-info": "4.1.2",
    "@storybook/addon-knobs": "4.1.2",
    "@storybook/addon-options": "4.1.2",
    "@storybook/cli": "4.1.2",
    "@storybook/react": "4.1.2",
```
is amazing

Am I doing something wrong?
