### ISSUE TITLE
Angular 6  Expected 'styles' to be an array of strings. 

### ISSUE THREAD

**Issue by wuyuanyi135** [storybooks/storybook#3593]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
I want to use storybook with **Angular 6**. It turns out I have to use the 4.0.0 alpha branch to make it through (#3044 ). After I managed to make the story server run, I got another error `Expected 'styles' to be an array of strings.`, which I have no idea how to get around.

### Steps to reproduce
I followed the instructions in https://storybook.js.org/basics/guide-angular/#docs-content but at the beginning the compilation failed: 
```
node_modules/webpack/lib/DefinePlugin.js:42
		compiler.hooks.compilation.tap(
		               ^

TypeError: Cannot read property 'compilation' of undefined
```

Then I installed @storybook/angular@4.0.0-alpha.6. I managed to run the server, but when I load my component, it shows
```
Expected 'styles' to be an array of strings.
            Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (http://localhost:9001/static/preview.bundle.js:8372:19)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:9001/static/preview.bundle.js:17242:13)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata (http://localhost:9001/static/preview.bundle.js:17887:28)
    at http://localhost:9001/static/preview.bundle.js:17536:53
    at Array.map (<anonymous>)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:9001/static/preview.bundle.js:17536:18)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (http://localhost:9001/static/preview.bundle.js:29551:51)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (http://localhost:9001/static/preview.bundle.js:29532:36)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (http://localhost:9001/static/preview.bundle.js:29492:37)
    at CompilerImpl../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (http://localhost:9001/static/preview.bundle.js:54699:31)
        
```
### Please specify which version of Storybook and optionally any affected addons that you're running

- "@ storybook/angular": "4.0.0-alpha.6",

**Comment by wuyuanyi135** [comment]
@nglazov I suppose that will be taken care of by the dev teams. :) Really hope it to work soon.

**Comment by enten** [comment]
Does [interface NgStory](https://github.com/storybooks/storybook/blob/4ea76066d1227db51cae4e93b68a098e4751e8cb/app/angular/src/client/preview/angular/types.ts#L13) correct?

How about `templateUrl` and `stylesUrl`?

```diff
export interface NgStory {
  component?: any;
  props: ICollection;
  propsMeta?: ICollection;
  moduleMetadata?: NgModuleMetadata;
  template?: string;
+ templateUrl?: string;
  styles?: string[];
+ styleUrls?: string[];
}
```

**Comment by agalazis** [comment]
@wuyuanyi135 your workaround seems to work that's the way it should be shipped (In my cas I didn't need the id part but your webpack config is a must)

**Comment by wuyuanyi135** [comment]
@agalazis True. I believe it was after alpha 7 where the `module.id` line was no longer necessary.

**Comment by igor-dv** [comment]
Has anyone tried the latest alpha? it supports Angular 6.

**Comment by DmitryEfimenko** [comment]
I'm still struggling to make it work. A part of the issue might be the fact that I'm using `.scss` files. @wuyuanyi135 , do you have an idea what webpack configuration to use in this case? I tried the suggested loader, but that didn't work:
```
{
  test: /\.scss$/,
  use: [
    'style-loader', // creates style nodes from JS strings
    'css-loader', // translates CSS into CommonJS
    'sass-loader' // compiles Sass to CSS
  ]
}
```

**Comment by igor-dv** [comment]
If you are using scss and angular-cli, storybook should work without configuring anything.

**Comment by ryaninvents** [comment]
I fixed this issue by using `text-loader`. I'm not using a CSS preprocessor though.

**Comment by igor-dv** [comment]
I assume we are ok here, right?

**Comment by MatissJanis** [comment]
I'm using alpha.14 and experiencing the same issue, but with `LESS` files rather than `SASS`.

**Comment by igor-dv** [comment]
AFAIR, `less` is also treated out-of-the-box by `angular-cli`, if so, you don't need to define any extra rules for the `.less` files.

**Comment by MatissJanis** [comment]
Sadly, removing the `.less` rule does not resolve the issue, but introduces a new one:

```
ERROR in ./.storybook/container.less 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '~@org/fe-webapp-styling/src/main.less';
|
 @ ./.storybook/config.js 10:0-26
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./src/components/molecules/progress-bar/progress-bar.component.less 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .progress-bar-warning {
|   width: 0;
| }
 @ ./src/components/molecules/progress-bar/progress-bar.component.ts 61:21-61
 @ ./src/components/molecules/progress-bar/index.ts
 @ ./src/components/molecules/index.ts
 @ ./src/components/index.ts
 @ ./src/components.module.ts
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

By the looks of it, `angular-cli` does not add the `less` loader to storybook, but it does work when running `ng build`.

**Comment by igor-dv** [comment]
I've added this 👇  to an official storybook angular example

![image](https://user-images.githubusercontent.com/7867954/42817809-e6101dfa-89d7-11e8-9418-3b4cb30c798f.png)

The only error I got is about the lack of less-loader, because we didn't choose this option when created our angular-cli example. After manually installing a less-loader, everything started working for me.

**Comment by MatissJanis** [comment]
Could you please give me a URL to the example commit? I'm trying to reproduce it locally, but failing.

**Comment by MatissJanis** [comment]
I fixed the issue by changing the LESS loader to this:

```
{
	test: /\.less$/,
	loaders: ['text-loader', 'style-loader', 'css-loader', 'less-loader'],
	include: path.resolve(__dirname, '../'),
}
```

Honestly - no idea why it works now.

**Comment by igor-dv** [comment]
I didn't commit this specific example. since there was nothing special. The official example app is [here ](https://github.com/storybooks/storybook/tree/master/examples/angular-cli), though, you need to bootstrap the whole monorepo to be able to run it.

Anyway, to understand what is wrong in your setup we need a reproduction 🤷‍♂️

**Comment by MatissJanis** [comment]
Yeah, that's completely understandable. Since I somehow managed to solve the issue on my project, I'll get out of your hair. Thanks for the patience! :)

**Comment by westandy-dcp** [comment]
I followed @wuyuanyi135 solution.  

1) I added a `.storybook/webpack.config.js` file code is below.
2) I added `to-string-loader` and `@storybook/addon-storysource` (alpha 4.0.0 version)

Here's my webpack code (same as @wuyuanyi135): 
```
const path = require('path');

module.exports = baseConfig => {
  // Extend defaultConfig as you need.

  baseConfig.module.rules = [
    ...baseConfig.module.rules,
    {
      test: [/\.stories\.tsx?$/, /index\.ts$/],
      loaders: [
        {
          loader: require.resolve('@storybook/addon-storysource/loader'),
          options: {
            parser: 'typescript'
          }
        }
      ],
      include: [path.resolve(__dirname, '../src')],
      enforce: 'pre'
    },
    {
      test: /\.css$/,
      use: ['to-string-loader', 'css-loader']
    }
  ];

  return baseConfig;
};
```

Adding `.less` to my project looks straightforward now.  Thank you, @wuyuanyi135 !

**Comment by iftkharhussain** [comment]
**i have fixed this issue** with changing
`styleUrls: ['./app.component.CSS']` to `styleUrls: ['./app.component.css']`

just lower case styles extensions
now it works fine :)

**Comment by mtuzinskiy** [comment]
@DmitryEfimenko Hi Dmitry! How did you solve your issue with `.scss` back then? I know that it should "just work", but it doesn't in my case, just like in yours

**Comment by jlowcs** [comment]
This error could be caused by a improper (ie too new) version of `raw-loader`.

See https://github.com/TheLarkInn/angular2-template-loader/issues/86

Setting it to `1.0.0` fixed the issue in my project.

**Comment by AviwT** [comment]
> This error could be caused by a improper (ie too new) version of `raw-loader`.
> 
> See [TheLarkInn/angular2-template-loader#86](https://github.com/TheLarkInn/angular2-template-loader/issues/86)
> 
> Setting it to `1.0.0` fixed the issue in my project.

Thanx man!
`raw-loader` v. `3.0.0` also has the same issue

**Comment by omares** [comment]
To fix the `Expected 'styles' to be an array of strings` error, i followed the [Custom Webpack Config chapter of the storybook documentation](https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode) and added a custom rule that handles `scss` parsing.

The debug flag ` --debug-webpack` revealed that storybook adds a custom `scss` rule which needs to removed, as that rule would still take priority of our custom one.

The final version of the customization looks as follow.

* JavaScript (`webpack.config.js`) version

```
// Export a function. Accept the base config as the only param.
module.exports = async ({config, mode}) => {
    // `mode` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    r = config.module.rules.filter(rule => rule.test != '/\\.s(c|a)ss$/');

    // Make whatever fine-grained changes you need
    r.push({
        test: /\.scss$/,
        // test: /\.s(c|a)ss$/,
        use: [
            'to-string-loader',
            {
                loader: 'style-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'css-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'sass-loader',
                options: {
                    sourceMap: true,
                },
            },
        ],
    });

    config.module.rules = r;

    // Return the altered config
    return config;
};
```

* TypeScript (`webpack.config.ts`) version with type hints

```
import {Configuration, RuleSetRule} from 'webpack';

module.exports = async ({config, mode}: {config: Configuration, mode: string}) => {
    // `mode` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    if (!config.module) {
        return config;
    }

    var rules = config.module.rules.filter((rule: RuleSetRule) => rule.test != '/\\.s(c|a)ss$/');

    rules.push({
        test: /\.scss$/,
        use: [
            'to-string-loader',
            {
                loader: 'style-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'css-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'sass-loader',
                options: {
                    sourceMap: true,
                },
            },
        ],
    });

    config.module.rules = rules;

    // Return the altered config
    return config;
};
```

**Comment by gn-sky** [comment]
Instead of ‘**style-loader**’, ‘css-loader’, ‘sass-loader’
I went with ‘**to-string-loader**’, ‘css-loader’, ‘sass-loader’
I used this article:
https://www.freecodecamp.org/news/how-to-configure-webpack-4-with-angular-7-a-complete-guide-9a23c879f471/
