### ISSUE TITLE
Storybook fails to compile after upgrading Next.js to v6.0.3

### ISSUE THREAD

**Issue by sebastian-veggiani-globant** [storybooks/storybook#3624]
### Storybook fails to compile after upgrading Next to v6.0.3

After upgrading Next.js to v6.0.3 my previously working setup stopped working.

The reported error is:

```
ERROR in ./.storybook/config.js
Module build failed: Error: Plugin 0 specified in "c:\\....\\node_modules\\next\\babel.js" provided an invalid property of "default" (While processing preset: "c:\\...\\node_modules\\next\\babel.js")
```

### Steps to reproduce

Upgrade a Next project from v5.1 to v6.0.3.

UPDATE: downgrading to v5.1 fixes the problem.

### Storybook versions

- storybook/react 3.4.5
- storybook/addon-info 3.4.5

### .stoyboojk/config.js

```js
import { configure } from '@storybook/react';
import '../src/styles/main.scss'

const req = require.context('../src', true, /stories\.js$/)

function loadStories() {
  req.keys().forEach(req)
}

configure(loadStories, module);
```

**Comment by suphareuk** [comment]
I have same error with Next v6 too.
It look like Storybook has problem with root .babelrc
I fixed by provided a custom .babelrc in .storybook folder

**Comment by thulstrup** [comment]
@suphareuk What's in your .babelrc in .storybook folder?

**Comment by revolunet** [comment]
for me :

``
`json
{
  "presets": ["next/babel"],
  "plugins": [
    "react-require"
  ]
}
```

**Comment by sebastian-veggiani-globant** [comment]
@revolunet using yarn here. running `yarn` before initializing `storybook` doesn't solve the problem for me...

**Comment by suphareuk** [comment]
@thulstrup 
This is my `.babelrc` setting in `.storybook` folder
```
{
  "presets": ["env", "stage-0", "react"]
}
```

**Comment by thulstrup** [comment]
@suphareuk Thanks! That did the trick for me as well.
