### ISSUE TITLE
Display possible PropTypes.oneOf values

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#790]
<a href="https://github.com/kevinSuttle"><img src="https://avatars0.githubusercontent.com/u/95672?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kevinSuttle](https://github.com/kevinSuttle)**
_Wednesday Jun 29, 2016 at 17:45 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/35_

----

``` js
import React from 'react';
require('./Headings.css');

const headingTypes = {
 page: <h1 />,
 modal: <h2 />,
 section: <h3 />,
 sub: <h4 />,
}

const Heading = ({ type, children }) => {
  const headingElement = headingTypes[type]
  return React.cloneElement(headingElement, {
    className: `${type}Heading`,
  }, ...children)
}

Heading.propTypes = {
  type: React.PropTypes.oneOf(Object.keys(headingTypes)).isRequired,
}

export default Heading;
```

Here's what I would expect to see, given the following story.

``` js
.addWithInfo(
    'simple usage (inline info)',
    `
      Section Heading API usage
    `,
    () => (<Heading type="section")}>Section Heading</Heading>),
    { inline: true },
  );
```

| property | propType | default | oneOf | required |
| --- | --- | --- | --- | --- |
| `type` | `string` | `page` | `page` `modal` `section` `sub` | <span color="red">true</span> |
|  |  |  |  |  |

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Wednesday Jun 29, 2016 at 17:47 GMT_

----

We'd like to do that. But, it's not possible to get this at runtime without hijacking PropTypes code.
That's why it's not there now.

@mnmtanish @roonyh May be we need to hijack PropTypes to get these.

**Comment by shilman** [comment]
<a href="https://github.com/kevinSuttle"><img src="https://avatars0.githubusercontent.com/u/95672?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevinSuttle](https://github.com/kevinSuttle)**
_Wednesday Jun 29, 2016 at 17:49 GMT_

----

Interesting.

**Comment by GabrielDuarteM** [comment]
Is someone looking into this? i'd love to see this working!

Now it seems kinda broken when using oneOf proptypes, because it simply shows a blank space

**Comment by danielduan** [comment]
This should be working if you have react-docgen working. It supports `oneOf` among other things and lists the contents inside an array.

**Comment by PaulieScanlon** [comment]
Hi, is this still outstanding? I have `react-docgen` working but `oneOf`still displays `-`

**Comment by danielduan** [comment]
I wonder if this is related to https://github.com/reactjs/react-docgen/issues/235

Just checked in our example app and it looks like the propType indeed doesn't work.

**Comment by priley86** [comment]
Noticing the same issue after attempting to upgade all my storybook packages to 3.3.3... 

when setting a propType using `oneOf` alongside `withInfo` addon, I now see the following error with addon-info `3.3.3`. I did not see this issue when using the deprecated API and [3.2.12]( https://github.com/patternfly/patternfly-react/blob/master/package.json#L33)

`Alert.js`:
```
import ClassNames from 'classnames';
import React from 'react';
import PropTypes from 'prop-types';
import { ALERT_TYPES, ALERT_TYPE_ERROR } from './constants';

const Alert = ({ children, className, onDismiss, type, ...props }) => {
  ...
};
Alert.propTypes = {
  /** additional alert classes */
  className: PropTypes.string,
  /** callback when alert is dismissed  */
  onDismiss: PropTypes.func,
  /** the type of alert  */
  type: PropTypes.oneOf(ALERT_TYPES).isRequired,
  /** children nodes  */
  children: PropTypes.node
};
```

`constants.js`:
```
export const ALERT_TYPE_DANGER = 'danger';
export const ALERT_TYPE_ERROR = 'error';
export const ALERT_TYPE_WARNING = 'warning';
export const ALERT_TYPE_SUCCESS = 'success';
export const ALERT_TYPE_INFO = 'info';

export const ALERT_TYPES = [
  ALERT_TYPE_DANGER,
  ALERT_TYPE_ERROR,
  ALERT_TYPE_WARNING,
  ALERT_TYPE_SUCCESS,
  ALERT_TYPE_INFO
];
```

Error:
```
index.js:16 TypeError: propType.value.map is not a function
    at OneOf (OneOf.js:20)
    at mountIndeterminateComponent (react-dom.development.js:8032)
    at beginWork (react-dom.development.js:8221)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at renderRoot (react-dom.development.js:10366)
    at performWorkOnRoot (react-dom.development.js:11014)
```

**Comment by priley86** [comment]
after debugging a bit...seems that `OneOf` definition [here](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/types/OneOf.js#L4) is accepting literals but not `import`'d types.

**Comment by Hypnosphi** [comment]
Should be fixed with https://github.com/storybooks/storybook/pull/2653

**Comment by Hypnosphi** [comment]
Released [3.3.14](https://github.com/storybooks/storybook/releases/tag/v3.3.14)

**Comment by dmk255** [comment]
The fix does not take into account all use cases of oneOf. In our case we have a select number of keys where share the same shape (specifically, this is a theme for styled components). I would prefer not to have to repeat the same shape.

The following still does not work:
```JS
 theme: t.shape({
    checkbox: t.objectOf(t.shape({
      [t.oneOf(CheckboxWrapped.checkboxTypes)]: t.shape({
        size: t.number,
        iconName: t.string,
        borderRadius: t.string,
        [t.oneOf(['checked', 'unchecked'])]: {
          background: t.string,
          borderColor: t.string,
          color: t.string,
        },
      }),
    })),
  }),
```
