### ISSUE TITLE
prop-types compatibility

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#954]
<a href="https://github.com/rota-rossi"><img src="https://avatars0.githubusercontent.com/u/7060081?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rota-rossi](https://github.com/rota-rossi)**
_Wednesday Apr 12, 2017 at 18:03 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/145_

----

right now the addon does not recognize the propTypes if using the new prop-types module.

#### import {PropTypes} from 'react'
<img width="370" alt="screen shot 2017-04-12 at 13 50 44" src="https://cloud.githubusercontent.com/assets/7060081/24971775/14dd5506-1f87-11e7-8184-8416825b2b4c.png">

#### import PropTypes from 'prop-types'
<img width="396" alt="screen shot 2017-04-12 at 13 48 25" src="https://cloud.githubusercontent.com/assets/7060081/24971727/e7f88e52-1f86-11e7-8e17-a43d1764847f.png">

**Comment by wejendorp** [comment]
Pretty sure this should work with the current state of the package. The dist folder on npm `3.4.0` is with `React.PropTypes` though.
Any update on getting a release to npm?

**Comment by ndelangen** [comment]
This will be a known bug in `3.0.0-alpha.0`

**Comment by chrisvxd** [comment]
So given the release of `3.1.2` just now (what happened to `3.1.0`?), which milestone is a fix for this pitched for?

**Comment by ndelangen** [comment]
I'm seeing this working locally, is this fixed now?

**Comment by shilman** [comment]
@chrisvxd sorry for the confusion here.
- lerna publish crashed halfway through 3.1.0/3.1.1 releases, so 3.1.2 is the first release where all the packages were released properly.
- i believe this fix is still getting reviewed/merged, and will go out with 3.1.3. i updated the milestones accordingly

**Comment by ndelangen** [comment]
Is this now resolved?

**Comment by TimGraf** [comment]
I'm seeing this issue again in v3.2.13.
